### ISSUE TITLE
Peer to peer code review - Hummingbird.

### ISSUE THREAD

**Issue by xtrmdarc** [elmejdki/HC_Capstone_Project#1]
- Good compact code.
- Recommendation: Use more CSS flexbox.
- Good work.
- Check recommended breakpoints. Tablet and desktop view looks the same.
- Nice work.
- Recommendation: Use (icons,svg) instead of images.
- Fix navbar and header on a lower mobile resolution.

**Comment by elmejdki** [comment]
thank u guys for your feedback :)
